#PlaceholderAPI:
# sc_coins - кол-во коинов игрока.
# sc_money - кол-во денег игрока.
# sc_coins_formatted - кол-во коинов игрока в отформатированном виде (см. ниже plural, singular, plural2).
# sc_money_formatted - кол-во денег игрока в отформатированном виде (см. ниже plural, singular, plural2).
# sc_coins_top_player_%место% - ник игрока по указанному индексу, если индекс больше чем playerTop->coinsCount - выведется пустое значение.
# sc_money_top_player_%место% - ник игрока по указанному индексу, если индекс больше чем playerTop->balanceCount - выведется пустое значение.
# sc_coins_top_%место% - баланс игрока по указанному индексу, если индекс больше чем playerTop->coinsCount - выведется пустое значение.
# sc_money_top_%место% - баланс игрока по указанному индексу, если индекс больше чем playerTop->balanceCount - выведется пустое значение.
# sc_coins_top_formatted_%место% - баланс игрока в отформатированном виде по указанному индексу, если индекс больше чем playerTop->coinsCount - выведется пустое значение.
# sc_money_top_formatted_%место% - баланс игрока в отформатированном виде по указанному индексу, если индекс больше чем playerTop->balanceCount - выведется пустое значение.

#Доступные хранилища: jedis, file
storage: file

#Будет ли функционировать команда /pay (актуально для серверов мини-игр)
payCommandEnabled: true

#Настройка redis хранилища
jedis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0
  balanceKey: "sc-balance-key"
  coinsKey: "sc-coins-key"

#Максимально допустимый баланс игрока
maxBalance: 500000
maxCoins: 100000

#Стартовый баланс игрока, при условии отсутствия данных в базе.
startBalance: 100
startCoins: 10

#Минимальная сумма денег которую игрок может перевести через /pay
minTransactionSum: 100

#Настройки топа.
playerTop:
  #Будет ли работать команда /baltop и обновления топа (актуально для серверов мини-игр)
  isEnabled: true
  #Кол-во игроков в топе по монеткам.
  balanceCount: 10
  #Кол-во игроков в топе по коинам.
  coinsCount: 10
  #Интервал обновления топов
  updateInterval: 1m

currencyFormat:
  plural: 'монетки'
  singular: 'монета'
  plural2: 'монеток'

currencyCoinsFormat:
  plural: 'коины'
  singular: 'коин'
  plural2: 'коинов'