#Доступные хранилища: mysql, redis, file
storage: mysql

#Настройка mysql хранилища
mysql:
  host: localhost
  port: 3306
  database: db
  username: mysql
  password: mysql
  table: 'scon_surv'
  useSSL: false

#Настройка redis хранилища
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  database: 0

#Максимально допустимый баланс игрока
maxBalance: 500000
maxCoins: 100000

#Стартовый баланс игрока, при условии отсутствия данных в базе.
startBalance: 100
startCoins: 10

#Минимальная сума денег которую он может перевести через /pay
minTransactionSum: 100

#Настройки топа.
playerTop:
  #Кол-во игроков в топе по монеткам.
  moneyCount: 10
  #Кол-во игроков в топе по коинам.
  coinsCount: 10
  #Интервал обновления топов
  updateInterval: 1m
  topFormat: "(index). (player) (balance)"

currencyFormat:
  plural: 'монетки'
  singular: 'монета'
  plural2: 'монеток'

currencyCoinsFormat:
  plural: 'коины'
  singular: 'коин'
  plural2: 'коинов'